###*
# Custom `color picker` extension
###

Storytime.ColorPickerExtension = MediumEditor.Extension.extend(
    name: 'colorPicker'
    init: ->
        @button = @document.createElement('button')
        @button.classList.add 'medium-editor-action'
        @button.classList.add 'editor-color-picker'
        @button.title = 'Text color'
        @button.innerHTML = '<i class="fa fa-paint-brush"></i>'
        @on @button, 'click', @handleClick.bind(this)
        return
    getButton: ->
        @button
    handleClick: (e) ->
        e.preventDefault()
        e.stopPropagation()
        @selectionState = @base.exportSelection()
        # If no text selected, stop here.
        if @selectionState and @selectionState.end - (@selectionState.start) == 0
            return
        # colors for picker
        pickerColors = [
            '#1abc9c'
            '#2ecc71'
            '#3498db'
            '#9b59b6'
            '#34495e'
            '#16a085'
            '#27ae60'
            '#2980b9'
            '#8e44ad'
            '#2c3e50'
            '#f1c40f'
            '#e67e22'
            '#e74c3c'
            '#bdc3c7'
            '#95a5a6'
            '#f39c12'
        ]
        picker = vanillaColorPicker(@document.querySelector('.medium-editor-toolbar-active .editor-color-picker').parentNode)
        picker.set 'customColors', pickerColors
        picker.set 'positionOnTop'
        picker.openPicker()
        picker.on 'colorChosen', ((color) ->
            @base.importSelection @selectionState
            @document.execCommand 'styleWithCSS', false, true
            @document.execCommand 'foreColor', false, color
            return
        ).bind(this)
        return
)

# ---
# generated by js2coffee 2.2.0