###*
# Custom `color picker` extension
###

Storytime.ColorPickerExtension = MediumEditor.Extension.extend(
    name: 'colorPicker'
    init: ->
        @button = @document.createElement('button')
        @button.classList.add 'medium-editor-action'
        @button.classList.add 'editor-color-picker'
        @button.title = 'Text color'
        @button.innerHTML = '<i class="fa fa-paint-brush"></i>'
        @on @button, 'click', @handleClick.bind(this)
        return
    getButton: ->
        @button
    handleClick: (e) ->
        e.preventDefault()
        e.stopPropagation()
        @selectionState = @base.exportSelection()
        # If no text selected, stop here.
        if @selectionState and @selectionState.end - (@selectionState.start) == 0
            return
        # colors for picker
        pickerColors = [
            '#000000'
            '#c0c0c0'
            '#808080'
            '#ffffff'
            '#800000'
            '#ff0000'
            '#800080'
            '#ff00ff'
            '#008000'
            '#00ff00'
            '#808000'
            '#ffff00'
            '#000080'
            '#0000ff'
            '#008080'
            '#00ffff'
        ]
        picker = vanillaColorPicker(@document.querySelector('.medium-editor-toolbar-active .editor-color-picker').parentNode)
        picker.set 'customColors', pickerColors
        picker.set 'positionOnTop'
        picker.openPicker()
        picker.on 'colorChosen', ((color) ->
            @base.importSelection @selectionState
            @document.execCommand 'styleWithCSS', false, true
            @document.execCommand 'foreColor', false, color
            return
        ).bind(this)
        return
)

# ---
# generated by js2coffee 2.2.0